### ISSUE TITLE
It would be nice that plcredits and plversion commands are categorized in the help command list.

### ISSUE THREAD

**Issue by ocformula** [Drapersniper/PyLav#289]
It would be nice that plcredits and plversion commands are categorized in the help command list.
Currently, the plcredits and plversion commands are not categorized and displayed separately from the other pylav commands.

**Comment by Drapersniper** [comment]
These commands are added by the library and not the cogs, hence them being separated.

If I add some logic to group them somewhere it would be red-specific since red's help formatted is what groups them based on cogs which is not something I'm willing to do on a library level. 

Theres not many ways in which I can solve this and all of the ones I can think off (dummy cog on lib init with the commands, is the first one that comes to mind) are not acceptable.
